# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93227b36e85397ca46197ddd479e94b9c81774835cb841dacf001202717e2aa0ea40cc78f342e0a18598d172abba5283debe544c55ab3c20d7f964673ecd3379

test:
  secret_key_base: 4dde4c4beefaca71a54e75a34486b00872076acbfb3f913561a1f12132dd9061b9b8668506e7c2dd9fc6e930a0b57034aed97340e6e4f58123ee1136daef7a04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
